name: dirise
description: Flutter project.

publish_to: "none"

version: 1.0.40+63

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^8.1.1
  flutter_pin_code_fields:
  pin_code_fields:
  google_maps_flutter:
  google_api_headers: ^2.0.3
  geocoding: ^3.0.0
  flutter_google_places_hoc081098: any
  cupertino_icons: ^1.0.6
  # carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  client_information: ^2.1.3
  get: ^4.6.5
  shared_preferences: ^2.2.1
  flutter_svg: ^2.0.7
  google_fonts: ^6.1.0
  collection: ^1.16.0
  flutter_rating_bar: ^4.0.1
  http: ^1.1.0
  sign_in_with_apple: ^6.1.2
  country_code_picker:
  pinput: ^3.0.1
  fluttertoast: ^8.2.2
  flutter_slidable: ^3.0.0
  dotted_border: ^2.1.0
  table_calendar: ^3.0.9
  form_field_validator: ^1.1.0
  google_sign_in: ^6.1.5
  firebase_auth: ^5.1.3
  flutter_switch: ^0.3.2
  loading_animation_widget: ^1.2.0+4
  shimmer: ^3.0.0
  intl:
  card_swiper: ^3.0.0
  file_picker: ^8.0.5
  image_picker: ^1.0.4
  internet_connection_checker: ^1.0.0+1
  cached_network_image: ^3.3.0
  flutter_math_fork: ^0.7.1
  scroll_loop_auto_scroll:
  open_filex: ^4.3.4
  lottie: ^2.6.0
  firebase_core: ^3.3.0
  firebase_messaging: ^15.0.4
  flutter_html:
  flutter_animate: ^4.2.0+1
  syncfusion_flutter_pdfviewer: ^26.1.40
  audioplayers: ^5.2.0
  audio_video_progress_bar: ^2.0.1
  flutter_local_notifications: ^17.2.1+2
  flutter_exif_rotation: ^0.5.1
  webview_flutter: ^4.2.4
  url_launcher: ^6.1.15
  better_player_plus:
  chewie: ^1.7.0
  video_player: ^2.8.2
  full_screen_image: ^2.0.0
  image_cropper: ^5.0.1
  hive:
  hive_flutter: ^1.1.0
  #  firebase_crashlytics: ^3.3.0
  firebase_analytics: ^11.3.0
  intl_phone_field: ^3.2.0
  color:
  easy_image_viewer: ^1.4.2
  flutter_exit_app: ^1.1.2
  pdf:
  auto_size_text: ^3.0.0
  photo_view: ^0.15.0
  dropdown_search: ^5.0.6
  carousel_slider: ^5.0.0
  device_info_plus: ^9.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/videos/
    - assets/icons/
    - assets/loti/
    - assets/svgs/
